[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Gruvbox-Material-Dark-Soft-v1
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Gruvbox-Material-Dark-Soft-v1
GtkTheme=Gruvbox-Material-Dark-Soft-v1
IconTheme=Gruvbox-Material-Dark-Soft-v1
MetacityTheme=Gruvbox-Material-Dark-Soft-v1
